version: "3.4"

services:

  pos1_1:
    image: "nara7875/openethereum:10"
    tty: true
    ports:
      - 8647:8647
      - 30315:30315
      - 10646:10646
    environment:
      ENV: ETHERNODE1
      RPCPORT: 8647
      PORT: 30315
      RUST_BACKTRACE: 1
    volumes:
      - ./config1.toml:/openethereum/config.toml
      - ./genesis1.json:/openethereum/genesis.json
      - ./password:/openethereum/password
      - ./nodes:/openethereum/nodes
      - ./keys1:/openethereum/keys
    container_name: pos1_1
    command: >
      sh -c "cd ~/
            /openethereum/target/release/openethereum --config /openethereum/config.toml"
    working_dir: /openethereum


  pos2_1:
    image: "nara7875/openethereum:10"
    tty: true
    ports:
      - 30316:30316
    environment:
      ENV: ETHERNODE2
      RPCPORT: 8647
      PORT: 30316
      RUST_BACKTRACE: 1
    volumes:
      - ./config2.toml:/openethereum/config.toml
      - ./genesis1.json:/openethereum/genesis.json
      - ./password:/openethereum/password
      - ./nodes:/openethereum/nodes
      - ./keys2:/openethereum/keys
    container_name: pos2_1
    command: >
      sh -c "cd ~/
            /openethereum/target/release/openethereum --config /openethereum/config.toml"
    working_dir: /openethereum

  scan:
    image: "nara7875/acentscan:17"
    ports:
      - 3013:3000
    restart: always
    depends_on:
      - db_1
    links:
      - pos1_1:pos1_1
    volumes:
      - ./config1.json:/config.json
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      MONGO_URI: mongodb://host.docker.internal/blockDB
    command : bash -c "/wait-for-it.sh -h mongo -p 27017 -t 30 -- npm run start"

  faucet:
    image: "nara7875/acentfaucet:1"
    ports:
      - 3014:3001
    restart: always
    volumes:
      - ./config.json:/config.json
      - ./.env:/.env
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    command : bash -c "/wait-for-it.sh -h mongo -p 27017 -t 30 -- npm run start"
  
  db_1:
    image: "mongo"
    depends_on:
      - pos1_1
      - pos2_1
    ports: 
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: "[blockDB]"